server.port: 9999

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: gateway-ecommerce
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: http://localhost:4200
                allowedHeaders: '*'
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
          routes:
            - id: billing-route
              uri: lb://billing
              predicates:
                - Path=/api/v1/customers/me/orders/{orderId}/invoice
                - Method=GET
            - id: ordering-route
              uri: lb://ordering
              predicates:
                - Path=/api/v1/orders/**,/api/v1/customers/**
            - id: product-catalog-route
              uri: lb://product-catalog
              predicates:
                - Path=/api/v1/products/**,/api/v1/categories/**
                - Method=GET,POST,PUT,DELETE,OPTIONS
            - id: product-catalog-test-route
              uri: lb://product-catalog
              predicates:
                - Path=/products/**
              filters:
                - RewritePath=/products/?(?<segment>.*), /api/v1/products$\{segment}
                - AddResponseHeader=X-Path-rewrite-info, Path have been rewrite to /api/v1/products
            - id: user-management-route
              uri: lb://authorization-server
              predicates:
                - Path=/api/v1/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: health, gateway
  endpoint:
    gateway:
      enabled: true